import { Link } from "react-router-dom";

const IndianaDisclaimer = () => {
  return (
    <div className="bg-background min-h-screen py-14">
      <div className="container mx-auto px-4 max-w-3xl">
        <h1 className="text-3xl sm:text-4xl font-display font-black text-foreground mb-2">
          Legal & Disclaimer
        </h1>
        <p className="text-muted-foreground text-sm mb-10">Last updated: February 2026</p>

        <div className="prose prose-sm max-w-none space-y-6 text-foreground/80 font-body leading-relaxed">
          <h2 className="text-xl font-display font-bold text-foreground mt-0 mb-4">Independence & Non-Affiliation</h2>
          <p>
            Fanpact is an <strong>INDEPENDENT, UNOFFICIAL</strong> eCommerce platform and is <strong>NOT</strong> affiliated with, endorsed by, licensed by, or operated by Indiana University, Indiana Athletics, its athletic department, NIL collective, or any official university entity.
          </p>

          <h2 className="text-xl font-display font-bold text-foreground mt-8 mb-4">Donation Model</h2>
          <p>
            We are a private company that donates <strong>50%</strong> of net operating earnings from qualifying purchases made through this platform to support Indiana University student-athletes and athletics programs (via NIL collectives or other permissible channels).
          </p>

          <h2 className="text-xl font-display font-bold text-foreground mt-8 mb-4">Storefront Disclaimer</h2>
          <p>
            This is <strong>NOT</strong> an official Indiana University storefront, and no University trademarks, logos, or official branding are used with permission. Any mention of "Indiana," "Hoosiers," or related terms is for descriptive purposes only to indicate the beneficiary of our voluntary donations.
          </p>

          <h2 className="text-xl font-display font-bold text-foreground mt-8 mb-4">How Donations Work</h2>
          <p>
            Your "Purchase Contribution" shown at checkout is an estimate of the donation generated by your purchase. The actual donation amount is approximately 18–20% of the purchase price, depending on product margins and category. Donations are tracked internally and distributed quarterly to qualifying NIL collectives or permissible athletic support channels.
          </p>
          <ul className="list-disc pl-6 space-y-3">
            <li>Donation percentages vary by product category and vendor margin.</li>
            <li>Only qualifying purchases (completed, non-refunded orders) count toward donations.</li>
            <li>Distributions occur on a quarterly basis; amounts are audited internally.</li>
            <li>Fanpact reserves the right to adjust the donation model with prior notice.</li>
          </ul>

          <h2 className="text-xl font-display font-bold text-foreground mt-8 mb-4">Thank You</h2>
          <p>
            Your purchases help support the Hoosiers—thank you for shopping with purpose!
          </p>
        </div>

        <div className="mt-10">
          <Link
            to="/indiana"
            className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-semibold transition-colors"
          >
            ← Back to Indiana Home
          </Link>
        </div>
      </div>
    </div>
  );
};

export default IndianaDisclaimer;
