// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-schools.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { schools } from "npm:@/data/schools";
var list_schools_default = defineTool({
  name: "list_schools",
  title: "List schools",
  description: "List all schools in the FanPact catalog. Optionally filter by conference (SEC, Big Ten, Big 12, ACC).",
  inputSchema: {
    conference: z.string().optional().describe("Optional conference name to filter by, e.g. 'SEC' or 'Big Ten'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ conference }) => {
    const filtered = conference ? schools.filter((s) => s.conference.toLowerCase() === conference.toLowerCase()) : schools;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { count: filtered.length, schools: filtered }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { allCategories as mizzouCategories } from "npm:@/data/mizzouCategoryData";
import { allCategories as indianaCategories } from "npm:@/data/indianaCategoryData";
import { allCategories as butlerCategories } from "npm:@/data/butlerCategoryData";
var bySchool = {
  missouri: mizzouCategories,
  mizzou: mizzouCategories,
  indiana: indianaCategories,
  butler: butlerCategories
};
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List product categories",
  description: "List product categories and subcategories for a FanPact storefront (missouri, indiana, or butler).",
  inputSchema: {
    school: z2.enum(["missouri", "mizzou", "indiana", "butler"]).describe("Storefront to list categories for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ school }) => {
    const cats = bySchool[school];
    const summary = cats.map((c) => ({
      slug: c.slug,
      name: c.name,
      description: c.description,
      subcategories: c.subcategories,
      productCount: c.products.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { school, categories: summary }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { allCategories as mizzouCategories2 } from "npm:@/data/mizzouCategoryData";
import { allCategories as indianaCategories2 } from "npm:@/data/indianaCategoryData";
import { allCategories as butlerCategories2 } from "npm:@/data/butlerCategoryData";
var bySchool2 = {
  missouri: mizzouCategories2,
  mizzou: mizzouCategories2,
  indiana: indianaCategories2,
  butler: butlerCategories2
};
var search_products_default = defineTool3({
  name: "search_products",
  title: "Search products",
  description: "Search products in a FanPact storefront by keyword. Optionally filter by category slug. Returns up to 25 matches with NIL contribution amounts.",
  inputSchema: {
    school: z3.enum(["missouri", "mizzou", "indiana", "butler"]).describe("Storefront to search."),
    query: z3.string().describe("Keyword to match against product name or brand."),
    category: z3.string().optional().describe("Optional category slug to restrict the search.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ school, query, category }) => {
    const cats = bySchool2[school];
    const q = query.trim().toLowerCase();
    const pool = category ? cats.filter((c) => c.slug === category) : cats;
    const matches = [];
    for (const c of pool) {
      for (const p of c.products) {
        if (p.name.toLowerCase().includes(q) || p.brand.toLowerCase().includes(q)) {
          matches.push({
            id: p.id,
            name: p.name,
            brand: p.brand,
            isNameBrand: p.isNameBrand,
            price: p.price,
            nilContribution: p.nilDonation,
            rating: p.rating,
            reviews: p.reviews,
            category: c.slug,
            subcategory: p.subcategory
          });
          if (matches.length >= 25) break;
        }
      }
      if (matches.length >= 25) break;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(matches, null, 2) }],
      structuredContent: { school, query, count: matches.length, products: matches }
    };
  }
});

// src/lib/mcp/tools/get-roster.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
import { sportRosters } from "npm:@/data/sportsRosters";
var get_roster_default = defineTool4({
  name: "get_roster",
  title: "Get sport roster",
  description: "Get the Missouri Tigers athlete roster for a given sport (e.g. football, mens-basketball, womens-basketball, baseball, softball, soccer, volleyball).",
  inputSchema: {
    sport: z4.string().describe("Sport slug, e.g. 'football' or 'volleyball'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ sport }) => {
    const key = sport.toLowerCase();
    const roster = sportRosters[key];
    if (!roster) {
      const available = Object.keys(sportRosters);
      return {
        content: [
          { type: "text", text: `No roster for '${sport}'. Available: ${available.join(", ")}` }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(roster, null, 2) }],
      structuredContent: { sport: key, count: roster.length, players: roster }
    };
  }
});

// src/lib/mcp/tools/nil-contribution.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var nil_contribution_default = defineTool5({
  name: "calculate_nil_contribution",
  title: "Calculate FanPact NIL contribution",
  description: "Calculate the FanPact NIL contribution for a purchase amount. Formula: 0.5 \xD7 (price \xD7 0.25).",
  inputSchema: {
    price: z5.number().positive().describe("Item or cart subtotal price in USD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ price }) => {
    const contribution = Math.round(0.5 * (price * 0.25) * 100) / 100;
    return {
      content: [
        {
          type: "text",
          text: `FanPact NIL Contribution on $${price.toFixed(2)} = $${contribution.toFixed(2)}`
        }
      ],
      structuredContent: { price, contribution, formula: "0.5 * (price * 0.25)" }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "fanpact-mcp",
  title: "FanPact MCP",
  version: "0.1.0",
  instructions: "Tools for the FanPact platform. Browse schools, product categories, and products across the Missouri, Indiana, and Butler storefronts; look up Missouri athlete rosters; and calculate the FanPact NIL contribution for any purchase amount (formula: 0.5 \xD7 price \xD7 0.25). All data is public catalog content.",
  tools: [list_schools_default, list_categories_default, search_products_default, get_roster_default, nil_contribution_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
